### ISSUE TITLE
windows 7 close maximize and minimize buttons gone

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [teknixstuff2/revert8plus#1]
aero appears to be working. buttons gone.

**Comment by teknixstuff2** [comment]
Run `%windir%\Revert8Plus\ApplyTheme`

**Comment by SuperMarioYAHOOYAHOO** [comment]
> Run `%windir%\Revert8Plus\ApplyTheme`

thanks, this worked!
